name: Автоматизация сборки

on:
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu-20.04
        env:
            HOSTS: ${{ secrets.ALLOWED_HOSTS }}
            SECRET: ${{ secrets.SECRET_KEY }}
            DEBUG: ${{ secrets.DEBUG }}
            DB_ENGINE: ${{ secrets.DB_ENGINE }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
        services:
            postgres_main:
                image: postgres:16
                env:
                    POSTGRES_DB: ${{ env.DB_NAME }}
                    POSTGRES_USER: ${{ env.DB_USER }}
                    POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
                ports:
                    - 5432:5432
                options:
                    --health-cmd pg_isready
                    --health-interval 5s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - name: Проверяем репозиторий на наличие изменений
              uses: actions/checkout@v4
            - name: Установка Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.11"
            - name: Установка зависимостей
              run: pip install -r requirements.txt
            - name: Линтинг
              run: flake8 logistic/ --exclude logistic/migrations
            - name: Тестирование
              run: python manage.py test